###############################################################
#  Generated by:      Cadence Innovus 21.11-s130_1
#  OS:                Linux x86_64(Host ID et4351.ewi.tudelft.nl)
#  Generated on:      Tue Apr  7 16:33:39 2026
#  Design:            et4351
#  Command:           routeDesign -globalDetail
###############################################################
current_design et4351
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 16.000000 -waveform {0.000000 8.000000}
create_generated_clock -name flash_clk -source [get_ports {clk}] -divide_by 2 [get_ports {flash_clk}]
set_propagated_clock  [get_ports {flash_clk}]
set_propagated_clock  [get_ports {clk}]
set_load -pin_load -max  0.05  [get_ports {ser_tx}]
set_load -pin_load -min  0.05  [get_ports {ser_tx}]
set_load -pin_load -max  0.05  [get_ports {flash_csb}]
set_load -pin_load -min  0.05  [get_ports {flash_csb}]
set_load -pin_load -max  0.05  [get_ports {flash_clk}]
set_load -pin_load -min  0.05  [get_ports {flash_clk}]
set_load -pin_load -max  0.05  [get_ports {flash_io0}]
set_load -pin_load -min  0.05  [get_ports {flash_io0}]
set_load -pin_load -max  0.05  [get_ports {flash_io1}]
set_load -pin_load -min  0.05  [get_ports {flash_io1}]
set_load -pin_load -max  0.05  [get_ports {flash_io2}]
set_load -pin_load -min  0.05  [get_ports {flash_io2}]
set_load -pin_load -max  0.05  [get_ports {flash_io3}]
set_load -pin_load -min  0.05  [get_ports {flash_io3}]
set_input_delay -add_delay 4 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io1}]
set_input_delay -add_delay 9 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io1}]
set_input_delay -add_delay 4 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io2}]
set_input_delay -add_delay 9 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io2}]
set_input_delay -add_delay 4 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io3}]
set_input_delay -add_delay 9 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io3}]
set_input_delay -add_delay 4 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io0}]
set_input_delay -add_delay 9 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io0}]
set_output_delay -add_delay 0 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io1}]
set_output_delay -add_delay 5 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io1}]
set_output_delay -add_delay 0 -min -clock [get_clocks {flash_clk}] [get_ports {flash_csb}]
set_output_delay -add_delay 5 -max -clock [get_clocks {flash_clk}] [get_ports {flash_csb}]
set_output_delay -add_delay 0 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io2}]
set_output_delay -add_delay 5 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io2}]
set_output_delay -add_delay 0 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io3}]
set_output_delay -add_delay 5 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io3}]
set_output_delay -add_delay 0 -min -clock [get_clocks {flash_clk}] [get_ports {flash_io0}]
set_output_delay -add_delay 5 -max -clock [get_clocks {flash_clk}] [get_ports {flash_io0}]
set_clock_uncertainty 0.25 [get_clocks {flash_clk}]
set_clock_uncertainty 0.25 [get_clocks {clk}]
set_false_path  -to [get_ports {ser_tx}] 
set_false_path  -from [get_ports {resetn ser_rx}] 
